export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

import { ThemeProvider } from '@lib/ui';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import '@lib/ui/styles/global.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const messages = useMessages();
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <NextIntlClientProvider locale="en" messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
