export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

import { DashboardLayout, SidebarProvider } from '@thor-commerce/ui';

import '@thor-commerce/ui/global.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <DashboardLayout>{children}</DashboardLayout>
    </SidebarProvider>
  );
}
