export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

import Providers from '@/providers/AuthProvider';

import '@thor-commerce/ui/global.css';
import { getServerSession } from 'next-auth';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return <Providers session={session}>{children}</Providers>;
}
