export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

import { auth } from '@dash/common/helpers';
import Providers from '@dash/providers/AuthProvider';

import '@thor-commerce/ui/global.css';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  console.log('Session in RootLayout:', session);
  return <Providers session={session}>{children}</Providers>;
}
