AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 1024

Resources:
  FlashCardsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: ./dist
      Environment:
        Variables:
          NODE_ENV: development
          DATABASE_URL: ${env:DB_URL}
          DB_USERNAME: ${env:DB_USERNAME}
          DB_PASSWORD: ${env:DB_PASSWORD}
          DB_NAME:
          DB_PORT: 5432
          COGNITO_USER_POOL_ID: ${aws_cognito_user_pool_id}
          COGNITO_CLIENT_ID: ${aws_cognito_client_id}
          COGNITO_REGION: us-east-1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
