name: Security & Quality Checks

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Security audit
      - name: Run security audit
        run: yarn audit --audit-level moderate

      # Code quality checks
      - name: TypeScript type checking
        run: yarn nx affected -t typecheck

      - name: Security checks passed
        run: echo "✅ All security and quality checks passed!"
