name: Security & Quality Checks
env:
  NX_BASE: main # Base branch for affected commands
  NX_NO_CLOUD: true # Disable Nx Cloud for this workflow

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Code quality checks
      - name: TypeScript type checking
        run: yarn nx affected -t typecheck --base=origin/main --parallel --maxParallel=4

      - name: Security checks passed
        run: echo "✅ All security and quality checks passed!"
